export class CollectorRepository {
  constructor(database, onError = () => {}) { this.database = database; this.onError = onError; this.pending = []; this.observations = new Map(); this.maxPending = 2000; this.metrics = { maxQueue:0,flushes:0,flushErrors:0,written:0,coalesced:0,dropped:0,lastPersistAt:null,lastPersistLatencyMs:null }; this.timer = setInterval(() => this.safeFlush(),1000); this.timer.unref?.(); }
  enqueue(sql, values) { if (this.pending.length >= this.maxPending) { this.metrics.dropped++; return; } this.pending.push([sql,values]); this.metrics.maxQueue = Math.max(this.metrics.maxQueue,this.pending.length+this.observations.size); if (this.pending.length >= 50) this.safeFlush(); }
  drainObservations() { for (const item of this.observations.values()) this.enqueue("INSERT INTO discovery_observations(discovery_run_id,account_id,occurred_at,last_seen_at,category,direction,target,ui_surface,location,size_bytes,fingerprint,metadata_json,seen_count) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(discovery_run_id,fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=discovery_observations.seen_count+excluded.seen_count,size_bytes=COALESCE(discovery_observations.size_bytes,0)+COALESCE(excluded.size_bytes,0),metadata_json=excluded.metadata_json",[item.runId,item.accountId,item.firstAt,item.lastAt,item.category,item.direction||null,item.target||null,item.uiSurface||null,item.location||null,item.sizeBytes,item.fingerprint,JSON.stringify(item.metadata),item.seenCount]); this.observations.clear(); }
  flush() { this.drainObservations(); if (!this.pending.length) return 0; const started = Date.now(),batch = this.pending.splice(0); this.database.exec("BEGIN IMMEDIATE"); try { for (const [sql,values] of batch) this.database.prepare(sql).run(...values); this.database.exec("COMMIT"); this.metrics.flushes++; this.metrics.written += batch.length; this.metrics.lastPersistAt = new Date().toISOString(); this.metrics.lastPersistLatencyMs = Date.now()-started; return batch.length; } catch (error) { try { this.database.exec("ROLLBACK"); } catch {} this.pending.unshift(...batch); throw error; } }
  safeFlush() { try { return this.flush(); } catch (error) { this.metrics.flushErrors++; try { this.onError(error); } catch {} return 0; } }
  close() { clearInterval(this.timer); this.safeFlush(); }
  status() { return { ...this.metrics,pending:this.pending.length+this.observations.size }; }
  sample(accountId, sessionRunId, snapshot) { const now = snapshot.capturedAt || new Date().toISOString(); this.enqueue("INSERT INTO telemetry_samples(account_id,session_run_id,captured_at,player_level,player_xp,pokemon_name,pokemon_level,pokemon_hp,location,bag_used,bag_capacity,gold,balls,snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [accountId, sessionRunId || null, now, snapshot.identity?.level ?? null, snapshot.identity?.xpPercent ?? null, snapshot.pokemon?.name ?? null, snapshot.pokemon?.level ?? null, snapshot.pokemon?.hp ?? null, snapshot.location?.current ?? null, snapshot.inventory?.used ?? null, snapshot.inventory?.capacity ?? null, snapshot.wallet?.gold ?? null, snapshot.inventory?.balls ?? null, JSON.stringify(snapshot)]); }
  gameEvent(accountId, sessionRunId, type, payload = {}) { this.enqueue("INSERT INTO game_events(account_id,session_run_id,occurred_at,type,payload_json) VALUES(?,?,?,?,?)", [accountId, sessionRunId || null, new Date().toISOString(), type, JSON.stringify(payload)]); }
  endpoint({ origin, path, method, resourceType }) { const now = new Date().toISOString(); this.enqueue("INSERT INTO network_endpoints(origin,path_pattern,method,resource_type,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?) ON CONFLICT(origin,path_pattern,method,resource_type) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [origin, path, method, resourceType, now, now]); }
  observeMap(label) { const match = String(label).match(/^(.+?)\s+Nv\s*(\d+)/i), clean = String(label).trim(); if (!clean) return; const key = clean.toLocaleLowerCase("pt-BR"); const now = new Date().toISOString(); this.enqueue("INSERT INTO map_observations(map_key,label,level,first_seen_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT(map_key) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [key, match?.[1]?.trim() || clean, match ? Number(match[2]) : null, now, now]); }
  discoverUi({ fingerprint, surface, label, selectorHint = null, metadata = {} }) { const now = new Date().toISOString(); this.enqueue("INSERT INTO ui_discoveries(fingerprint,surface,label,selector_hint,first_seen_at,last_seen_at,metadata_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [fingerprint, surface, label, selectorHint, now, now, JSON.stringify(metadata)]); }
  listMaps() { this.safeFlush(); return this.database.prepare("SELECT map_key AS key,label,level,city,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM map_observations ORDER BY label").all(); }
  listEndpoints(limit = 300) { this.safeFlush(); return this.database.prepare("SELECT origin,path_pattern AS path,method,resource_type AS resourceType,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM network_endpoints ORDER BY last_seen_at DESC LIMIT ?").all(Math.max(1,Math.min(1000,Number(limit)||300))); }
  startDiscovery(accountId, mode = "MANUAL", reason = null) { return Number(this.database.prepare("INSERT INTO discovery_runs(account_id,started_at,mode,reason) VALUES(?,?,?,?)").run(accountId || null, new Date().toISOString(), mode, reason).lastInsertRowid); }
  stopDiscovery(id) { return this.database.prepare("UPDATE discovery_runs SET ended_at=? WHERE id=? AND ended_at IS NULL").run(new Date().toISOString(), id).changes > 0; }
  discoverySummary(id) { this.safeFlush(); const totals=this.database.prepare("SELECT COUNT(*) facts,COALESCE(SUM(seen_count),0) observations,COUNT(DISTINCT CASE WHEN category='WEBSOCKET' THEN target END) websockets,COUNT(DISTINCT CASE WHEN category='NETWORK' THEN target END) endpoints FROM discovery_observations WHERE discovery_run_id=?").get(id); return { facts:Number(totals.facts),observations:Number(totals.observations),websockets:Number(totals.websockets),endpoints:Number(totals.endpoints) }; }
  observation(item) { const key = `${item.runId}:${item.fingerprint}`,now = new Date().toISOString(),current = this.observations.get(key); if (current) { current.lastAt=now;current.seenCount++;current.sizeBytes=(current.sizeBytes||0)+(item.sizeBytes||0);current.metadata=item.metadata||{};this.metrics.coalesced++;return; } if (this.observations.size >= this.maxPending) { this.metrics.dropped++;return; } this.observations.set(key,{ ...item,firstAt:now,lastAt:now,seenCount:1,sizeBytes:item.sizeBytes||0,metadata:item.metadata||{} }); this.metrics.maxQueue=Math.max(this.metrics.maxQueue,this.pending.length+this.observations.size); }
  listObservations(limit = 300) { this.safeFlush(); return this.database.prepare("SELECT account_id AS accountId,occurred_at AS occurredAt,last_seen_at AS lastSeenAt,seen_count AS seenCount,category,direction,target,ui_surface AS uiSurface,location,size_bytes AS sizeBytes FROM discovery_observations ORDER BY last_seen_at DESC LIMIT ?").all(Math.max(1,Math.min(1000,Number(limit)||300))); }
  storageKey(accountId, storageType, keyName) { const now = new Date().toISOString(); this.enqueue("INSERT INTO storage_key_observations(account_id,storage_type,key_name,first_seen_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT(account_id,storage_type,key_name) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [accountId, storageType, keyName, now, now]); }
  retain({ telemetryDays = 7, discoveryDays = 14, discoveryRunDays = 90, gameEventDays = 30 } = {}) { this.safeFlush(); const result = {}; result.telemetry = this.database.prepare("DELETE FROM telemetry_samples WHERE julianday(captured_at) < julianday('now',?)").run(`-${telemetryDays} days`).changes; result.discovery = this.database.prepare("DELETE FROM discovery_observations WHERE julianday(occurred_at) < julianday('now',?)").run(`-${discoveryDays} days`).changes; result.discoveryRuns = this.database.prepare("DELETE FROM discovery_runs WHERE ended_at IS NOT NULL AND julianday(ended_at) < julianday('now',?)").run(`-${discoveryRunDays} days`).changes; result.gameEvents = this.database.prepare("DELETE FROM game_events WHERE julianday(occurred_at) < julianday('now',?)").run(`-${gameEventDays} days`).changes; return result; }
}
