export class CollectorRepository {
  constructor(database) { this.database = database; this.pending = []; this.timer = setInterval(() => this.flush(), 1000); this.timer.unref?.(); }
  enqueue(sql, values) { this.pending.push([sql, values]); if (this.pending.length >= 50) this.flush(); }
  flush() { if (!this.pending.length) return; const batch = this.pending.splice(0); this.database.exec("BEGIN IMMEDIATE"); try { for (const [sql, values] of batch) this.database.prepare(sql).run(...values); this.database.exec("COMMIT"); } catch (error) { this.database.exec("ROLLBACK"); this.pending.unshift(...batch); throw error; } }
  close() { clearInterval(this.timer); this.flush(); }
  sample(accountId, sessionRunId, snapshot) { const now = snapshot.capturedAt || new Date().toISOString(); this.enqueue("INSERT INTO telemetry_samples(account_id,session_run_id,captured_at,player_level,player_xp,pokemon_name,pokemon_level,pokemon_hp,location,bag_used,bag_capacity,gold,balls,snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [accountId, sessionRunId || null, now, snapshot.identity?.level ?? null, snapshot.identity?.xpPercent ?? null, snapshot.pokemon?.name ?? null, snapshot.pokemon?.level ?? null, snapshot.pokemon?.hp ?? null, snapshot.location?.current ?? null, snapshot.inventory?.used ?? null, snapshot.inventory?.capacity ?? null, snapshot.wallet?.gold ?? null, snapshot.inventory?.balls ?? null, JSON.stringify(snapshot)]); }
  gameEvent(accountId, sessionRunId, type, payload = {}) { this.enqueue("INSERT INTO game_events(account_id,session_run_id,occurred_at,type,payload_json) VALUES(?,?,?,?,?)", [accountId, sessionRunId || null, new Date().toISOString(), type, JSON.stringify(payload)]); }
  endpoint({ origin, path, method, resourceType }) { const now = new Date().toISOString(); this.enqueue("INSERT INTO network_endpoints(origin,path_pattern,method,resource_type,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?) ON CONFLICT(origin,path_pattern,method,resource_type) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [origin, path, method, resourceType, now, now]); }
  observeMap(label) { const match = String(label).match(/^(.+?)\s+Nv\s*(\d+)/i), clean = String(label).trim(); if (!clean) return; const key = clean.toLocaleLowerCase("pt-BR"); const now = new Date().toISOString(); this.enqueue("INSERT INTO map_observations(map_key,label,level,first_seen_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT(map_key) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [key, match?.[1]?.trim() || clean, match ? Number(match[2]) : null, now, now]); }
  discoverUi({ fingerprint, surface, label, selectorHint = null, metadata = {} }) { const now = new Date().toISOString(); this.enqueue("INSERT INTO ui_discoveries(fingerprint,surface,label,selector_hint,first_seen_at,last_seen_at,metadata_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [fingerprint, surface, label, selectorHint, now, now, JSON.stringify(metadata)]); }
  listMaps() { this.flush(); return this.database.prepare("SELECT map_key AS key,label,level,city,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM map_observations ORDER BY label").all(); }
  listEndpoints(limit = 300) { this.flush(); return this.database.prepare("SELECT origin,path_pattern AS path,method,resource_type AS resourceType,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM network_endpoints ORDER BY last_seen_at DESC LIMIT ?").all(Math.max(1,Math.min(1000,Number(limit)||300))); }
  startDiscovery(accountId, mode = "MANUAL", reason = null) { return Number(this.database.prepare("INSERT INTO discovery_runs(account_id,started_at,mode,reason) VALUES(?,?,?,?)").run(accountId || null, new Date().toISOString(), mode, reason).lastInsertRowid); }
  stopDiscovery(id) { return this.database.prepare("UPDATE discovery_runs SET ended_at=? WHERE id=? AND ended_at IS NULL").run(new Date().toISOString(), id).changes > 0; }
  observation(item) { this.enqueue("INSERT INTO discovery_observations(discovery_run_id,account_id,occurred_at,category,direction,target,ui_surface,location,size_bytes,fingerprint,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)", [item.runId, item.accountId, new Date().toISOString(), item.category, item.direction || null, item.target || null, item.uiSurface || null, item.location || null, item.sizeBytes ?? null, item.fingerprint, JSON.stringify(item.metadata || {})]); }
  listObservations(limit = 300) { this.flush(); return this.database.prepare("SELECT account_id AS accountId,occurred_at AS occurredAt,category,direction,target,ui_surface AS uiSurface,location,size_bytes AS sizeBytes FROM discovery_observations ORDER BY id DESC LIMIT ?").all(Math.max(1, Math.min(1000, Number(limit) || 300))); }
  storageKey(accountId, storageType, keyName) { const now = new Date().toISOString(); this.enqueue("INSERT INTO storage_key_observations(account_id,storage_type,key_name,first_seen_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT(account_id,storage_type,key_name) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1", [accountId, storageType, keyName, now, now]); }
  retain({ telemetryDays = 7, discoveryDays = 14, gameEventDays = 30 } = {}) { this.flush(); const result = {}; result.telemetry = this.database.prepare("DELETE FROM telemetry_samples WHERE julianday(captured_at) < julianday('now',?)").run(`-${telemetryDays} days`).changes; result.discovery = this.database.prepare("DELETE FROM discovery_observations WHERE julianday(occurred_at) < julianday('now',?)").run(`-${discoveryDays} days`).changes; result.gameEvents = this.database.prepare("DELETE FROM game_events WHERE julianday(occurred_at) < julianday('now',?)").run(`-${gameEventDays} days`).changes; return result; }
}
