export class CollectorRepository {
  constructor(database) { this.database = database; }
  sample(accountId, sessionRunId, snapshot) { const now = snapshot.capturedAt || new Date().toISOString(); return this.database.prepare("INSERT INTO telemetry_samples(account_id,session_run_id,captured_at,player_level,player_xp,pokemon_name,pokemon_level,pokemon_hp,location,bag_used,bag_capacity,gold,balls,snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(accountId, sessionRunId || null, now, snapshot.identity?.level ?? null, snapshot.identity?.xpPercent ?? null, snapshot.pokemon?.name ?? null, snapshot.pokemon?.level ?? null, snapshot.pokemon?.hp ?? null, snapshot.location?.current ?? null, snapshot.inventory?.used ?? null, snapshot.inventory?.capacity ?? null, snapshot.wallet?.gold ?? null, snapshot.inventory?.balls ?? null, JSON.stringify(snapshot)); }
  gameEvent(accountId, sessionRunId, type, payload = {}) { this.database.prepare("INSERT INTO game_events(account_id,session_run_id,occurred_at,type,payload_json) VALUES(?,?,?,?,?)").run(accountId, sessionRunId || null, new Date().toISOString(), type, JSON.stringify(payload)); }
  endpoint({ origin, path, method, resourceType }) { const now = new Date().toISOString(); this.database.prepare("INSERT INTO network_endpoints(origin,path_pattern,method,resource_type,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?) ON CONFLICT(origin,path_pattern,method,resource_type) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1").run(origin, path, method, resourceType, now, now); }
  observeMap(label) { const match = String(label).match(/^(.+?)\s+Nv\s*(\d+)/i), clean = String(label).trim(); if (!clean) return; const key = clean.toLocaleLowerCase("pt-BR"); const now = new Date().toISOString(); this.database.prepare("INSERT INTO map_observations(map_key,label,level,first_seen_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT(map_key) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1").run(key, match?.[1]?.trim() || clean, match ? Number(match[2]) : null, now, now); }
  discoverUi({ fingerprint, surface, label, selectorHint = null, metadata = {} }) { const now = new Date().toISOString(); this.database.prepare("INSERT INTO ui_discoveries(fingerprint,surface,label,selector_hint,first_seen_at,last_seen_at,metadata_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,seen_count=seen_count+1").run(fingerprint, surface, label, selectorHint, now, now, JSON.stringify(metadata)); }
  listMaps() { return this.database.prepare("SELECT map_key AS key,label,level,city,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM map_observations ORDER BY label").all(); }
  listEndpoints(limit = 300) { return this.database.prepare("SELECT origin,path_pattern AS path,method,resource_type AS resourceType,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,seen_count AS seenCount FROM network_endpoints ORDER BY last_seen_at DESC LIMIT ?").all(Math.max(1,Math.min(1000,Number(limit)||300))); }
  startDiscovery(accountId, mode = "MANUAL", reason = null) { return Number(this.database.prepare("INSERT INTO discovery_runs(account_id,started_at,mode,reason) VALUES(?,?,?,?)").run(accountId || null, new Date().toISOString(), mode, reason).lastInsertRowid); }
  stopDiscovery(id) { return this.database.prepare("UPDATE discovery_runs SET ended_at=? WHERE id=? AND ended_at IS NULL").run(new Date().toISOString(), id).changes > 0; }
}
