import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { CollectorCoordinator } from "../apps/desktop/main/collector/CollectorCoordinator.js";
import { openDatabase } from "../apps/desktop/main/storage/Database.js";
import { AccountRepository } from "../apps/desktop/main/storage/AccountRepository.js";
import { CollectorRepository } from "../apps/desktop/main/storage/CollectorRepository.js";
import { BootstrapService } from "../apps/desktop/main/services/BootstrapService.js";

function fixture(){const calls={ samples:[],game:[],events:[] },repository={ sample:(...x)=>calls.samples.push(x),gameEvent:(...x)=>calls.game.push(x),observeMap:()=>{},discoverUi:()=>{} },events={ add:x=>calls.events.push(x) },runs=new Map([["conta-01",7]]);return{ calls,coordinator:new CollectorCoordinator(repository,events,runs) };}
test("coordinator merges partial deltas without erasing canonical state",()=>{const{coordinator}=fixture();coordinator.ingest("conta-01",{ patch:{ identity:{ player:"ASH",level:10 },location:{ current:"Cerulean" } },changed:["identity","location"],ready:true });const result=coordinator.ingest("conta-01",{ patch:{ pokemon:{ name:"Pikachu",hp:50 } },changed:["pokemon"],ready:true });assert.equal(result.current.identity.player,"ASH");assert.equal(result.current.location.current,"Cerulean");assert.equal(result.current.pokemon.name,"Pikachu");});
test("coordinator emits semantic change once and ignores unknown UI controls",()=>{const{coordinator,calls}=fixture();coordinator.ingest("conta-01",{ patch:{ location:{ current:"Cerulean" } },changed:["location"] });coordinator.ingest("conta-01",{ patch:{ location:{ current:"Onix" } },changed:["location"] });coordinator.ingest("conta-01",{ patch:{ location:{ current:"Onix" } },changed:["location"] });assert.equal(calls.game.filter(x=>x[2]==="MAP_ENTERED").length,1);assert.equal(coordinator.recordUiAction("conta-01","✕"),false);assert.equal(coordinator.recordUiAction("conta-01","MAPA"),true);});
test("agent delta flows through coordinator into SQLite snapshot and semantic event",()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"vp-pipeline-")),database=openDatabase(path.join(directory,"test.db")),repository=new CollectorRepository(database);try{const accounts=new AccountRepository(database);new BootstrapService(database,accounts).run({ gameUrl:"https://pokewg.com/play",accounts:[{ id:"conta-01",name:"Conta 01" }] });const events={ add:()=>{} },coordinator=new CollectorCoordinator(repository,events,new Map([["conta-01",null]]));coordinator.ingest("conta-01",{ patch:{ identity:{ player:"ASH",level:10 },location:{ current:"Cerulean" } },changed:["identity","location"],ready:true });coordinator.ingest("conta-01",{ patch:{ location:{ current:"Onix" } },changed:["location"],ready:true });repository.flush();assert.equal(database.prepare("SELECT COUNT(*) total FROM telemetry_samples").get().total,2);assert.equal(database.prepare("SELECT type FROM game_events WHERE type='MAP_ENTERED'").get().type,"MAP_ENTERED");}finally{repository.close();database.close();fs.rmSync(directory,{ recursive:true,force:true });}});
