import assert from "node:assert/strict";import test from "node:test";import { DirectProvider,SystemProvider,ProxyProvider,ProtonProvider } from "../apps/desktop/main/network/providers.js";import { evaluatePolicy } from "../apps/desktop/main/network/NetworkResult.js";import { PreflightService } from "../apps/desktop/main/network/PreflightService.js";import { NetworkManager } from "../apps/desktop/main/network/NetworkManager.js";
import { redactFrame } from "../apps/desktop/main/collector/Redactor.js";
const fakeSession=()=>({calls:[],async setProxy(config){this.calls.push(["proxy",config]);},async closeAllConnections(){this.calls.push(["close"]);},async clearHostResolverCache(){this.calls.push(["dns"]);},async forceReloadProxyConfig(){this.calls.push(["reload"]);}});
test("direct and system apply distinct Electron proxy modes and cleanup",async()=>{for(const [Provider,mode] of [[DirectProvider,"direct"],[SystemProvider,"system"]]){const ses=fakeSession();await new Provider().apply(ses);assert.equal(ses.calls[0][1].mode,mode);assert.deepEqual(ses.calls.slice(1).map(x=>x[0]),["close","dns"]);}});
test("proxy supports validated protocols without credentials in URL",async()=>{const ses=fakeSession(),provider=new ProxyProvider({config:{protocol:"socks5",host:"127.0.0.1",port:1080}});await provider.apply(ses);assert.equal(ses.calls[0][1].proxyRules,"socks5://127.0.0.1:1080");assert.equal(provider.reconnectSupported,true);assert.throws(()=>new ProxyProvider({config:{protocol:"ftp",host:"x",port:1}}).validate());});
test("policy detects IP, prefix and country mismatch",()=>{assert.equal(evaluatePolicy({publicIp:"1.2.3.4",country:"BR"},{expectedCountry:"BR"}).status,"OK");assert.equal(evaluatePolicy({publicIp:"1.2.3.4",country:"US"},{expectedCountry:"BR"}).status,"MISMATCH");assert.equal(evaluatePolicy({publicIp:"1.2.3.4",country:"BR"},{expectedIpPrefix:"9."}).status,"MISMATCH");});
test("preflight timeout/failure never assumes success",async()=>{const service=new PreflightService({urls:["x"],timeoutMs:5}),result=await service.check({fetch:async()=>{throw new Error("offline");}});assert.equal(result.status,"UNREACHABLE");});
test("manager isolates providers and protected failure has no direct fallback",async()=>{const profiles=[{id:"direct",name:"Direct",type:"DIRECT",config:{}},{id:"a",name:"A",type:"PROXY",config:{protocol:"http",host:"a",port:8001}},{id:"b",name:"B",type:"PROXY",config:{protocol:"http",host:"b",port:8002}}],events=[],manager=new NetworkManager({repository:{list:()=>profiles},events:{add:x=>events.push(x)},preflight:{check:async(_s,p)=>({status:p.host==="bad"?"UNREACHABLE":"OK",publicIp:p.host||"direct"})}}),s1=fakeSession(),s2=fakeSession();await Promise.all([manager.prepare({accountId:"c1",profileId:"a",ses:s1}),manager.prepare({accountId:"c2",profileId:"b",ses:s2})]);assert.match(s1.calls[0][1].proxyRules,/a:8001/);assert.match(s2.calls[0][1].proxyRules,/b:8002/);assert.notDeepEqual(s1.calls[0],s2.calls[0]);assert.equal(new ProtonProvider({config:{host:"127.0.0.1",port:19001}}).support,"SUPPORTED_LOCAL_WORKER");});

test("critical isolation keeps C02 on B while C01 changes A to C",async()=>{const profiles=["a","b","c"].map((id,index)=>({id,name:id.toUpperCase(),type:"PROXY",config:{protocol:"http",host:id,port:8100+index}})),manager=new NetworkManager({repository:{list:()=>profiles},events:{add(){}},preflight:{check:async(_ses,p)=>({status:"OK",publicIp:`203.0.113.${p.host.charCodeAt(0)-96}`})}}),c1=fakeSession(),c2=fakeSession();const[first,second]=await Promise.all([manager.prepare({accountId:"c1",profileId:"a",ses:c1}),manager.prepare({accountId:"c2",profileId:"b",ses:c2})]);assert.equal(first.result.publicIp,"203.0.113.1");assert.equal(second.result.publicIp,"203.0.113.2");const changed=await manager.prepare({accountId:"c1",profileId:"c",ses:c1});assert.equal(changed.result.publicIp,"203.0.113.3");assert.equal(manager.status("c2").result.publicIp,"203.0.113.2");assert.equal(c2.calls.filter(x=>x[0]==="proxy").length,1);});

test("missing Vault credential fails closed before proxy apply",async()=>{const profile={id:"auth",name:"Auth",type:"PROXY",credentialId:"proxy:auth",config:{protocol:"http",host:"proxy",port:8080}},ses=fakeSession(),manager=new NetworkManager({repository:{list:()=>[profile]},events:{add(){}},credentialResolver:async()=>({state:"EMPTY"})});const state=await manager.prepare({accountId:"c1",profileId:"auth",ses});assert.equal(state.result.status,"CONFIG_ERROR");assert.equal(ses.calls.length,0);});

test("proxy authorization, VPN token and provider token are redacted",()=>{const result=redactFrame(JSON.stringify({"Proxy-Authorization":"Basic abc",proxyPassword:"secret",vpnToken:"vpn",providerToken:"provider"}));assert.deepEqual(result.preview,{"Proxy-Authorization":"[redacted]",proxyPassword:"[redacted]",vpnToken:"[redacted]",providerToken:"[redacted]"});});

test("new prepare cancels stale preflight and repeated operations remain serialized",async()=>{const profiles=[{id:"a",name:"A",type:"DIRECT",config:{}},{id:"b",name:"B",type:"SYSTEM",config:{}}],preflight={check:(_ses,_policy,signal)=>new Promise(resolve=>{const timer=setTimeout(()=>resolve({status:"OK",publicIp:"198.51.100.1"}),5);signal?.addEventListener("abort",()=>{clearTimeout(timer);resolve({status:"UNKNOWN",cancelled:true});},{once:true});})},manager=new NetworkManager({repository:{list:()=>profiles},events:{add(){}},preflight}),ses=fakeSession(),first=manager.prepare({accountId:"c1",profileId:"a",ses}),second=manager.prepare({accountId:"c1",profileId:"b",ses});assert.equal((await first).result.cancelled,true);assert.equal((await second).result.status,"OK");assert.equal(ses.calls.filter(x=>x[0]==="proxy").length,1);});
