import assert from "node:assert/strict";
import { createRequire } from "node:module";
import test from "node:test";
const require=createRequire(import.meta.url),{ applyReaders }=require("../apps/desktop/game-agent/readers/state-readers.cjs"),{ createDelta }=require("../apps/desktop/game-agent/state/delta.cjs");

test("readers extract known player, pokemon and inventory fixture",()=>{const state={ identity:null,location:{},pokemon:null,inventory:null,collection:null,wallet:null,game:{} };applyReaders("PENISPARKER LV 67 Mapa: Cerulean XP 42% Bulbasaur Lv. 58 HP 492 / 500 XP 12% Capacidade 1 / 335 Gold 1.910",state);assert.equal(state.identity.player,"PENISPARKER");assert.equal(state.identity.level,67);assert.equal(state.location.current,"Cerulean");assert.equal(state.pokemon.name,"Bulbasaur");assert.equal(state.inventory.capacity,335);assert.equal(state.wallet.gold,1910);});
test("readers leave unknown fields null",()=>{const state={ identity:null,location:{},pokemon:null,inventory:null,wallet:null,game:{} };applyReaders("texto sem telemetria",state);assert.equal(state.identity,null);assert.equal(state.pokemon,null);assert.equal(state.inventory,null);});
test("battle fractions never masquerade as inventory or location",()=>{const state={ identity:null,location:{},pokemon:null,inventory:null,wallet:null,game:{} };applyReaders("PENISPARKER LV 69 Onix XP 82% Bulbasaur Lv. 58 HP 312 / 588 XP 44%",state);assert.equal(state.location.current,undefined);assert.equal(state.inventory,null);assert.equal(state.pokemon.hp,312);});
test("delta ignores irrelevant duplicates and reports semantic top-level change",()=>{const previous={ identity:{ player:"ASH",level:10 },location:{ current:"Cerulean" } };assert.deepEqual(createDelta(previous,structuredClone(previous)),{ patch:{},changed:[] });const current={ ...previous,location:{ current:"Onix" } },delta=createDelta(previous,current);assert.deepEqual(delta.changed,["location"]);assert.deepEqual(delta.patch.location,{ current:"Onix" });});
