const $ = selector => document.querySelector(selector);
let timer;
async function tab() { const [value] = await chrome.tabs.query({active:true,currentWindow:true}); if(!value?.url||!/^https:\/\/(test\.)?pokewg\.com\/play/.test(value.url)) throw new Error("Abra o PokeWG na aba ativa."); return value; }
async function send(type, extra={}) { const current=await tab(); try{return await chrome.tabs.sendMessage(current.id,{type,...extra})}catch(error){if(!String(error.message).includes("Receiving end does not exist"))throw error;await chrome.scripting.executeScript({target:{tabId:current.id},files:["content.js"]});return chrome.tabs.sendMessage(current.id,{type,...extra})} }
const pct=(a,b)=>b?Math.max(0,Math.min(100,a/b*100)):0;
const text=(id,value)=>$(id).textContent=value??"—";
function render(state){const p=state.parsed?.player,m=state.parsed?.activePokemon,c=state.parsed?.capacity,a=state.parsed?.activity;$("#dot").classList.toggle("on",state.ready&&!a?.disconnected);text("#connection",state.ready?"Online":"Aguardando");text("#player",p?`${p.name} · Lv ${p.level} · ${p.xpPercent}%`:null);text("#location",a?.location);text("#last-hunt",state.lastHunt);text("#pokemon",m?`${m.name} · Lv ${m.level} · XP ${m.xpPercent}%`:null);text("#hp",m?`${m.hp}/${m.maxHp}`:null);$("#hp-fill").style.width=`${pct(m?.hp,m?.maxHp)}%`;text("#capacity",c?`${c.used}/${c.total}`:null);$("#capacity-fill").style.width=`${pct(c?.used,c?.total)}%`;const label=a?.disconnected?"Desconectado":a?.hunting?"Caçando":a?.inCity?"Na cidade":"Carregando";text("#activity",`${label}${a?.penalty?" · Penalidade XP":""}`);text("#updated",new Date(state.capturedAt).toLocaleTimeString("pt-BR"));$("#mode-monitor").classList.toggle("active",state.mode==="monitor");$("#mode-assisted").classList.toggle("active",state.mode==="assisted");$("#assist-actions").hidden=state.mode!=="assisted"}
async function refresh(){try{render(await send("VP_GET_LIVE_STATE"));$("#status").textContent=""}catch(error){$("#dot").classList.remove("on");text("#connection","Offline");$("#status").textContent=error.message}}
async function mode(value){const result=await send("VP_SET_MODE",{mode:value});if(!result.ok)throw new Error(result.error);await refresh()}
$("#mode-monitor").onclick=()=>mode("monitor").catch(e=>$("#status").textContent=e.message);$("#mode-assisted").onclick=()=>mode("assisted").catch(e=>$("#status").textContent=e.message);$("#refresh").onclick=refresh;
$("#prepare-sale").onclick=async()=>{$("#status").textContent="Preparando venda…";const result=await send("VP_PREPARE_SALE").catch(e=>({ok:false,error:e.message}));if(!result.ok){$("#status").textContent=result.error;return}const p=result.preview;$("#sale-preview").textContent=`${p.items.length} tipos · ${p.totalItems} itens · $${p.totalValue.toLocaleString("pt-BR")}`;$("#confirm-sale").disabled=!p.items.length;$("#status").textContent="Venda preparada. Confira antes de confirmar."};
$("#confirm-sale").onclick=async()=>{if(!confirm("Vender todo o loot listado? Esta ação altera inventário e saldo."))return;const result=await send("VP_CONFIRM_SALE").catch(e=>({ok:false,error:e.message}));$("#status").textContent=result.ok?`Venda enviada: ${result.confirmationText}`:result.error;if(result.ok)$("#confirm-sale").disabled=true};
$("#return-hunt").onclick=async()=>{if(!confirm("Retornar à última hunt memorizada?"))return;const result=await send("VP_RETURN_HUNT").catch(e=>({ok:false,error:e.message}));$("#status").textContent=result.ok?`Retornando para ${result.hunt}.`:result.error};
$("#full-cycle").onclick=async()=>{const button=$("#full-cycle");button.disabled=true;$("#status").textContent="Preparando ciclo…";const prepared=await send("VP_START_FULL_CYCLE").catch(e=>({ok:false,error:e.message}));if(!prepared.ok){$("#status").textContent=prepared.error;button.disabled=false;return}const p=prepared.preview;$("#sale-preview").textContent=`${p.items.length} tipos · ${p.totalItems} itens · $${p.totalValue.toLocaleString("pt-BR")} · retorno: ${prepared.lastHunt}`;if(!confirm(`Vender ${p.totalItems} itens por $${p.totalValue.toLocaleString("pt-BR")} e retornar para ${prepared.lastHunt}?`)){ $("#status").textContent="Pausado na tela de venda; nada foi vendido.";$("#confirm-sale").disabled=false;button.disabled=false;return }$("#status").textContent="Vendendo e retornando…";const result=await send("VP_COMPLETE_FULL_CYCLE").catch(e=>({ok:false,error:e.message}));$("#status").textContent=result.ok?`Concluído: $${result.sold.totalValue.toLocaleString("pt-BR")} · ${result.returnedTo}`:`Ciclo interrompido: ${result.error}`;button.disabled=false;await refresh()};
$("#capture").onclick=async()=>{try{const report=await send("VP_CAPTURE");const url=`data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(report,null,2))}`;const stamp=new Date().toISOString().replace(/[:.]/g,"-");await chrome.downloads.download({url,filename:`vp-client/diagnostico-${stamp}.json`,saveAs:false});$("#status").textContent="Diagnóstico salvo."}catch(error){$("#status").textContent=error.message}};
refresh();timer=setInterval(refresh,2000);window.addEventListener("unload",()=>clearInterval(timer));
