const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("vpNative", {
  accounts: () => ipcRenderer.invoke("vp:accounts"),
  openEmbedded: id => ipcRenderer.invoke("vp:open-embedded", id),
  layoutEmbedded: layouts => ipcRenderer.invoke("vp:layout-embedded", layouts),
  closeEmbedded: id => ipcRenderer.invoke("vp:close-embedded", id),
  reloadEmbedded: id => ipcRenderer.invoke("vp:reload-embedded", id),
  gameAction: payload => ipcRenderer.invoke("vp:game-action", payload),
  profiles: () => ipcRenderer.invoke("vp:profiles"),
  saveProfile: profile => ipcRenderer.invoke("vp:save-profile", profile),
  deleteProfile: id => ipcRenderer.invoke("vp:delete-profile", id),
  loginProfile: id => ipcRenderer.invoke("vp:login-profile", id),
  vaultStatus: () => ipcRenderer.invoke("vp:vault-status"),
  networkProfiles: () => ipcRenderer.invoke("vp:network-profiles"),
  saveNetworkProfile: profile => ipcRenderer.invoke("vp:save-network-profile", profile),
  presets: () => ipcRenderer.invoke("vp:presets"),
  savePreset: preset => ipcRenderer.invoke("vp:save-preset", preset),
  events: filter => ipcRenderer.invoke("vp:events", filter),
  collectorMaps: () => ipcRenderer.invoke("vp:collector-maps"),
  collectorEndpoints: limit => ipcRenderer.invoke("vp:collector-endpoints", limit),
  collectorObservations: limit => ipcRenderer.invoke("vp:collector-observations", limit),
  collectorStatus: () => ipcRenderer.invoke("vp:collector-status"),
  collectorHealth: id => ipcRenderer.invoke("vp:collector-health", id),
  onStateChanged: callback => { const listener = (_event,message) => callback(message); ipcRenderer.on("vp:state-changed",listener); return () => ipcRenderer.removeListener("vp:state-changed",listener); },
  startDiscovery: id => ipcRenderer.invoke("vp:start-discovery", id),
  stopDiscovery: id => ipcRenderer.invoke("vp:stop-discovery", id),
  getSetting: (key, fallback) => ipcRenderer.invoke("vp:get-setting", { key, fallback }),
  setSetting: (key, value) => ipcRenderer.invoke("vp:set-setting", { key, value }),
  updateAccount: update => ipcRenderer.invoke("vp:update-account", update)
});
