import { AccountSession,SessionState } from "./AccountSession.js";

export class SessionManager {
  constructor({ sessionRepository,eventRepository,publish=()=>{},maxRecoveryRetries=3 }) { this.sessionRepository=sessionRepository;this.events=eventRepository;this.publish=publish;this.maxRecoveryRetries=maxRecoveryRetries;this.sessions=new Map();this.operations=new Map(); }
  get(id) { if (!this.sessions.has(id)) this.sessions.set(id,new AccountSession(id)); return this.sessions.get(id); }
  snapshot(id) { return this.get(id).snapshot(); }
  list() { return [...this.sessions.values()].map(item=>item.snapshot()); }
  async serialize(id,work) { const prior=this.operations.get(id)||Promise.resolve();const next=prior.catch(()=>{}).then(work);this.operations.set(id,next);try{return await next;}finally{if(this.operations.get(id)===next)this.operations.delete(id);} }
  emit(session,to,reason,details={}) { const change=session.transition(to,reason,details);if(!change)return session.snapshot();this.events.add({ accountId:session.accountId,sessionRunId:session.sessionRunId,type:"SESSION_STATE_CHANGED",payload:change });this.publish(session.accountId,{ session:session.snapshot(),running:to!==SessionState.CLOSED });return session.snapshot(); }
  open(id,openView) { return this.serialize(id,async()=>{const s=this.get(id);if(s.state!==SessionState.CLOSED)return s.snapshot();s.generation++;s.retryCount=0;s.sessionRunId=this.sessionRepository.start(id);this.emit(s,SessionState.STARTING,"open-requested");try{await openView?.(s.generation);this.emit(s,SessionState.NETWORK_CHECK,"view-created");return s.snapshot();}catch(error){return this.fail(id,"OPEN_FAILED",error.message,false);} }); }
  network(id,result) { const s=this.get(id);if(s.state!==SessionState.NETWORK_CHECK)return s.snapshot();if(result==="FAILED")return this.fail(id,"NETWORK_FAILED","Network preflight failed",false);return this.emit(s,SessionState.AUTH_CHECK,result==="OK"?"network-ok":"network-unknown"); }
  auth(id,result) { const s=this.get(id);if(![SessionState.AUTH_CHECK,SessionState.AUTHENTICATING,SessionState.WAITING_USER].includes(s.state))return s.snapshot();const map={ AUTHENTICATED:SessionState.READY,LOGIN_REQUIRED:SessionState.AUTHENTICATING,LOADING:SessionState.AUTH_CHECK,CHALLENGE:SessionState.WAITING_USER,UNEXPECTED:SessionState.WAITING_USER };const to=map[result];if(!to||to===s.state)return s.snapshot();return this.emit(s,to,`auth-${result.toLowerCase()}`); }
  game(id,{ ready=false,hunting=false,disconnected=false }={},generation=null) { const s=this.get(id);if(generation!=null&&generation!==s.generation)return s.snapshot();if(disconnected)return this.recover(id,"game-disconnected");if(!ready)return s.snapshot();if([SessionState.AUTH_CHECK,SessionState.AUTHENTICATING,SessionState.RECOVERING].includes(s.state)){this.emit(s,SessionState.READY,"agent-authenticated");s.retryCount=0;}if(s.state===SessionState.PAUSED)return s.snapshot();if(hunting&&s.state===SessionState.READY)return this.emit(s,SessionState.HUNTING,"collector-hunting");if(!hunting&&s.state===SessionState.HUNTING)return this.emit(s,SessionState.READY,"collector-idle");return s.snapshot(); }
  pause(id) { const s=this.get(id);if(s.state===SessionState.PAUSED)return s.snapshot();if(![SessionState.READY,SessionState.HUNTING].includes(s.state))return s.snapshot();return this.emit(s,SessionState.PAUSED,"pause-requested"); }
  resume(id) { const s=this.get(id);if(s.state!==SessionState.PAUSED)return s.snapshot();return this.emit(s,s.previousActiveState===SessionState.HUNTING?SessionState.HUNTING:SessionState.READY,"resume-requested"); }
  beginAction(id,reason="action-started") { const s=this.get(id);if(![SessionState.READY,SessionState.HUNTING].includes(s.state))return s.snapshot();return this.emit(s,SessionState.ACTION_RUNNING,reason); }
  finishAction(id,reason="action-finished") { const s=this.get(id);if(s.state!==SessionState.ACTION_RUNNING)return s.snapshot();return this.emit(s,s.previousActiveState===SessionState.HUNTING?SessionState.HUNTING:SessionState.READY,reason); }
  recover(id,reason) { const s=this.get(id);if(s.state===SessionState.CLOSED)return s.snapshot();if(s.state===SessionState.ERROR){if(!s.error?.recoverable)return s.snapshot();this.emit(s,SessionState.RECOVERING,reason);}else if(s.state!==SessionState.RECOVERING)this.emit(s,SessionState.RECOVERING,reason);s.retryCount++;if(s.retryCount>this.maxRecoveryRetries)return this.fail(id,"RECOVERY_EXHAUSTED",`Recovery exhausted after ${this.maxRecoveryRetries} retries`,false);return s.snapshot(); }
  fail(id,code,message,recoverable=true) { const s=this.get(id);if(s.state===SessionState.CLOSED)return s.snapshot();const previousState=s.state;if(s.state!==SessionState.ERROR)this.emit(s,SessionState.ERROR,code.toLowerCase());s.error={ code,message,previousState,occurredAt:new Date().toISOString(),recoverable,retryCount:s.retryCount };this.publish(id,{ session:s.snapshot() });return s.snapshot(); }
  close(id,reason="USER_CLOSED",closeView) { return this.serialize(id,async()=>{const s=this.get(id);if(s.state===SessionState.CLOSED)return s.snapshot();const runId=s.sessionRunId;await closeView?.();this.emit(s,SessionState.CLOSED,reason.toLowerCase());if(runId)this.sessionRepository.end(runId,reason);s.sessionRunId=null;s.retryCount=0;s.error=null;this.publish(id,{ session:s.snapshot(),running:false });return s.snapshot();}); }
}
